// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSgKuEN-NWXLBCzHwVh85BrxuM54sVqM',
    appId: '1:115929333210:web:dd49f0654fca7dd9da14e3',
    messagingSenderId: '115929333210',
    projectId: 'twitter-clone-cb015',
    authDomain: 'twitter-clone-cb015.firebaseapp.com',
    storageBucket: 'twitter-clone-cb015.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQnODIEJG-t2Lev37_7TBDi6IPcgD9k04',
    appId: '1:115929333210:android:9b8eb5816b0eff24da14e3',
    messagingSenderId: '115929333210',
    projectId: 'twitter-clone-cb015',
    storageBucket: 'twitter-clone-cb015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOtpSf-C3Qw533jDFO325Js8g-RvWIUY',
    appId: '1:115929333210:ios:b91f9d5b4ad0f9d9da14e3',
    messagingSenderId: '115929333210',
    projectId: 'twitter-clone-cb015',
    storageBucket: 'twitter-clone-cb015.appspot.com',
    iosClientId: '115929333210-fsutvp3tf5o6u4o1d2k7f22c1k09idis.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOtpSf-C3Qw533jDFO325Js8g-RvWIUY',
    appId: '1:115929333210:ios:9cd46ef2a11f1f7eda14e3',
    messagingSenderId: '115929333210',
    projectId: 'twitter-clone-cb015',
    storageBucket: 'twitter-clone-cb015.appspot.com',
    iosClientId: '115929333210-pj905iqp6k0nik4h8q0b6deea7m78f5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
